development:
  adapter: mysql2
  url: <%= ENV['DATABASE_URL'] %>

test:
  adapter: mysql2
  url: <%= ENV['DATABASE_URL'] %>

production:
  adapter: mysql2
  url: <%= ENV['DATABASE_URL'] %>
  pool: 50
  timeout: 5000
